repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    - id: mypy

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8

-   repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
    - id: isort
