language: python
python:
  - "3.7"

# setting up stages for CI
stages:
  - Quality
  - Test

# cache definitions
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"


# jobs definitions for each stage
jobs:
  include:
    - stage: Quality
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files

    - stage: Test
      before_install:
        - pip install --upgrade pip
        - pip install poetry
      #  - poetry config virtualenvs.create false
      install:
        - poetry install -v
        - poetry add codecov
      script:
        - poetry run pytest --cov=configs tests/

  
# add notifications to slack: #pre-open-source channel
notifications:
  slack: appcard:X0eePYKUsQauXm1MksKI5WXU

# add codecov reports
after_success:
  - codecov
