name: Python package

on:
  push:
    branches:
      - main
      - develop
  
  pull_request:
    brnaches:
      - main
      - develop

jobs:

  quality_check_job:
    name: Quality
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: |
        pip install poetry
        poetry run pip install --upgrade pip
    - name: Install project
      run: |
        poetry install
    - name: Run quality pre-commit checks
      run: |
        poetry run pre-commit run --all-files
    - name: Test with pytest
      run: |
        poetry run pytest --cov=configs --cov-report=xml tests/
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        directory: ./coverage/reports/
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        verbose: true
        
  
